repos:
  - repo: local
    hooks:
      - id: commitizen-check
        name: Check commit message with commitizen
        entry: scripts/commitizen-check.sh
        language: script
        stages: [commit-msg]
        pass_filenames: true  # Pre-commit передает путь к файлу как аргумент скрипта
        always_run: true